name: flutter_onboarding_flow
description: A highly customizable onboarding flow package for Flutter with swipeable screens, progress indicators, templates, and accessibility support.
version: 1.0.0
homepage: https://github.com/Navid-Rahman/flutter_onboarding_flow

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
